# -*- coding: utf-8 -*-
"""Aumento de salario

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAcSzOzwGZHSoJ1tJbkf9bB6RMQG-lgf
"""

salario = float(input("Digite o salário do funcionário: "))

if salario < 500:
    novo_salario = salario + (salario * 0.15)
elif salario <= 1000:
    novo_salario = salario + (salario * 0.10)
else:
    novo_salario = salario + (salario * 0.05)

print(f"O novo salário do funcionário é: R$ {novo_salario:.2f}")