# -*- coding: utf-8 -*-
"""Calculo dobro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAcSzOzwGZHSoJ1tJbkf9bB6RMQG-lgf
"""

# Programa para calcular o dobro de um número

# Lendo o número
numero = int(input("Digite um número: "))

# Calculando o dobro
dobro = numero * 2

# Mostrando o resultado
print(f"O dobro é {dobro}")