# -*- coding: utf-8 -*-
"""Calculo Area de um Terreno.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAcSzOzwGZHSoJ1tJbkf9bB6RMQG-lgf
"""

# Programa para calcular a área de um terreno quadrado

# Lendo o tamanho do lado
lado = float(input("Digite o tamanho do lado do seu terreno: "))

# Calculando a área
area = lado * lado

# Exibindo o resultado
print(f"\nSua área é {area:.2f} m²")