# -*- coding: utf-8 -*-
"""Calculo horas de trabalho.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAcSzOzwGZHSoJ1tJbkf9bB6RMQG-lgf
"""

# Programa para calcular o pagamento diário e semanal

# Valor da hora
valor_por_hora = 30

# Lendo horas trabalhadas por dia
horas_dia1 = float(input("Quantas horas você trabalhou no dia 1? "))
print(f"Você receberá no dia 1: {horas_dia1 * valor_por_hora:.2f}")

horas_dia2 = float(input("\nQuantas horas você trabalhou no dia 2? "))
print(f"Você receberá no dia 2: {horas_dia2 * valor_por_hora:.2f}")

horas_dia3 = float(input("\nQuantas horas você trabalhou no dia 3? "))
print(f"Você receberá no dia 3: {horas_dia3 * valor_por_hora:.2f}")

horas_dia4 = float(input("\nQuantas horas você trabalhou no dia 4? "))
print(f"Você receberá no dia 4: {horas_dia4 * valor_por_hora:.2f}")

horas_dia5 = float(input("\nQuantas horas você trabalhou no dia 5? "))
print(f"Você receberá no dia 5: {horas_dia5 * valor_por_hora:.2f}")

# Calculando total da semana
horas_semana = horas_dia1 + horas_dia2 + horas_dia3 + horas_dia4 + horas_dia5
print(f"\nVocê receberá ao final da semana: {horas_semana * valor_por_hora:.2f}")