# -*- coding: utf-8 -*-
"""Dois valores inteiros

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAcSzOzwGZHSoJ1tJbkf9bB6RMQG-lgf
"""

# Programa para calcular resultado com base na comparação de dois números

# Entrada de dados
A = int(input("Digite o primeiro valor: "))
B = int(input("Digite o segundo valor: "))

# Processamento
if A == B:
    print(f"O valor é {A + B}")
elif A < B:
    print(f"O valor é {A - B}")
else:
    print(f"O valor é {A * B}")