# -*- coding: utf-8 -*-
"""Receba um valor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAcSzOzwGZHSoJ1tJbkf9bB6RMQG-lgf
"""

def inicio():
    valor = float(input("Digite um número: "))

    if valor > 0.0:
        print(valor * 2.0)
    elif valor < 0.0:
        print(valor * 3.0)
    else:
        print("Nada a fazer, o número digitado foi 0")


# executando a função
inicio()