# -*- coding: utf-8 -*-
"""Verificar maior numero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAcSzOzwGZHSoJ1tJbkf9bB6RMQG-lgf
"""

# Programa para descobrir o maior de três números

# Lendo os três valores
valor1 = float(input("Digite o primeiro valor: "))
valor2 = float(input("Digite o segundo valor: "))
valor3 = float(input("Digite o terceiro valor: "))

# Verificando qual é o maior número
if valor1 > valor2 and valor1 > valor3:
    print(f"O maior número é {valor1}")
elif valor2 > valor3 and valor2 > valor1:
    print(f"O maior número é {valor2}")
else:
    print(f"O maior número é {valor3}")