# -*- coding: utf-8 -*-
"""Verificar categoria do mebro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAcSzOzwGZHSoJ1tJbkf9bB6RMQG-lgf
"""

idade = int(input("Digite a idade do membro: "))

if 7 <= idade <= 10:
    print("Categoria: Infantil")
elif 11 <= idade <= 15:
    print("Categoria: Juvenil")
elif 16 <= idade <= 20:
    print("Categoria: Junior")
elif idade >= 21:
    print("Categoria: Profissional")
else:
    print("Idade fora das categorias")